
sudo: required

services:
  - docker

language: ruby

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.1
        - DOCKER_DIR=${TRAVIS_BUILD_DIR}/docker

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine
    # travis documentation says I'm in trusty container
    - lsb_release -a | grep trusty
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker version | grep ${DOCKER_ENGINE_VERSION}
    # smoke test
    - docker run --rm hello-world
    - docker images

script:
    - cd ${DOCKER_DIR}/nginx
    - ./build-image.sh
