
sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - ./build.sh && ./push.sh

# push.sh does the [docker push]
# I do not do the [docker push] in a travis after_success: section
# The reason is if [docker push] fails it does NOT fail the travis run.
# https://github.com/travis-ci/travis-ci/issues/758
