version: 2
jobs:
  build-image:
    steps:
      - checkout
    docker:
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker

      - run:
          name: build Geoserver docker image and push image to docker hub
          command: |
            docker build -t cyberdojo/nginx:$(git rev-parse --short=7 HEAD) .
            docker push cyberdojo/nginx:$(git rev-parse --short=7 HEAD)

  # deploy-to-dev:
  #   docker:
  #     - image: praqma/helmsman:v1.3.0-helm-v2.8.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: run helmsman
  #         command: |
  #           helmsman -debug -apply -f .circleci/helmsman-dev-deployment.toml
  # deploy-to-beta:
  #   docker:
  #     - image: praqma/helmsman:v1.3.0-helm-v2.8.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: run helmsman
  #         command: |
  #           helmsman -debug -apply -f .circleci/helmsman-beta-deployment.toml


workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                - master
