# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "nginx"

replicaCount: 3

service:
  port: 80

containers:
  - name: nginx
    image: cyberdojo/nginx
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 64Mi
    # livenessProbe:
    #   path: /sha
    #   port: 80
    # readinessProbe:
    #   path: /ready?
    #   port: 80

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
